baseURL: "https://cedarcreekadventure.com/"
title: Cedar Creek Adventure
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Cedar Creek Adventure
    description: "Cedar Creek Adventure"
    keywords: [Blog, Cedar Creek, Bio]
    #author: "Cedar Creek Adventure"
    author: ["Cedar Creek Adventure by Graeme Noble & Carissa Paulger"]
    images: ["openlogo.png"]
    DateFormat: "Monday 02 January 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "favicon.ico"
        favicon16x16: "favicon-16x16.png"
        favicon32x32: "favicon-32x32.png"
        apple_touch_icon: "apple-touch-icon.png"
        safari_pinned_tab: "apple-touch-icon.png"

    label:
        text: "Cedar Creek Adventure"
        icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: "Cedar Creek Adventure"
        subtitle: "This is subtitle"
        imageUrl: "openlogo.png"
        imageWidth: 120
        imageHeight: 120
        imageTitle: "Cedar Creek Adventure"
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    socialIcons:
        - name: instagram
          url: "https://instagram.com/cedarcreekadventure"
        - name: other
          url: "https://instagram.com/gmanual"

#    analytics:
#        google:
#            SiteVerificationTag: "XYZabc"
#        bing:
#            SiteVerificationTag: "XYZabc"
#        yandex:
#            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

#    editPost:
#        URL: "https://github.com/<path_to_repo>/content"
#        Text: "Suggest Changes" # edit text
#        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: categories
          name: categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20
#        - identifier: example
#          name: example.org
#          url: https://example.org
#          weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
